### ISSUE TITLE
bug: Issue with chained function calls without arguments or parenthesis.

### ISSUE THREAD

**Issue by nvergottini** [tree-sitter-grammars/tree-sitter-puppet#9]
### Did you check existing issues?

- [X] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [X] I have searched the existing issues

### Describe the bug

Using chained function calls with no arguments and without including empty parenthesis breaks all syntax highlighting within a block and all auto-indenting below the function call.

Without parenthesis:
![image](https://github.com/tree-sitter-grammars/tree-sitter-puppet/assets/28265335/6034b546-62aa-4929-aea8-26789fe4bc26)

With parenthesis:
![image](https://github.com/tree-sitter-grammars/tree-sitter-puppet/assets/28265335/1d727a0c-db0e-4152-ade1-00fefa4f2371)

I'm using Neovim 0.9.5 with Lazyvim. All plugins are up-to-date.

### Steps To Reproduce/Bad Parse Tree

Use any chained function call without arguments or parenthesis (each, map, filter, etc). This issue also affects using chained function calls without arguments or parenthesis in an if expression.

### Expected Behavior/Parse Tree

Using chained function calls without arguments shouldn't require empty parenthesis for proper syntax highlighting or auto-indenting. The Puppet style guide does not specify that empty parenthesis are required.

**Comment by amaanq** [comment]
is the parse tree messed up or just the queries, it'd be helpful to actually have more info that just screenshots of code

**Comment by nvergottini** [comment]
I don't know what you mean about the parse tree.

This would be simple example code.

```puppet
class test {
  $packages = [
    'package1',
    'package2',
  ]

  $packages.each |$package| {
    package { $package:
    ensure => installed,
  }
  }
}
```

In the screenshots you can see that the "each" function and the "package" resource statements don't highlight correctly compared to when using "each()". You will have to actually type in the code to see how auto-indent doesn't work correctly. I am just assuming here that it is tree-sitter that handles the auto-indent. I'm still somewhat new to Neovim.

I saw similar issues in VSCode years ago, but those have since been corrected.

**Comment by clason** [comment]
If you're using Neovim, `:InspectTree` will show you the parsed tree. Otherwise, `tree-sitter parse`.

**Comment by nvergottini** [comment]
Here is a new sample with indentation fixed and a comment so that it will pass puppet lint with no errors.

```puppet
# @summary Test class
class test {
  $packages = [
    'package1',
    'package2',
  ]

  # With empty paraenthesis.
  $packages.each() |$package| {
    package { $package:
      ensure => installed,
    }
  }

  # Without empty paraenthesis.
  $packages.each |$package| {
    package { $package:
      ensure => installed,
    }
  }
}
```

Here is the tree from :InspectTree.

```
(comment) ; [1:1 - 21]
(class_definition) ; [2:1 - 20:3]
 (identifier) ; [2:7 - 10]
 (block) ; [2:12 - 20:3]
  (assignment) ; [3:3 - 6:3]
   (variable) ; [3:3 - 11]
    (identifier) ; [3:4 - 11]
   (array) ; [3:15 - 6:3]
    (string) ; [4:5 - 14]
     (string_content) ; [4:6 - 13]
    (string) ; [5:5 - 14]
     (string_content) ; [5:6 - 13]
  (comment) ; [8:3 - 28]
  (variable) ; [9:3 - 11]
   (identifier) ; [9:4 - 11]
  (ERROR) ; [9:12 - 12]
  (function_call) ; [9:13 - 13:3]
   (identifier) ; [9:13 - 16]
   (lambda) ; [9:20 - 13:3]
    (variable) ; [9:21 - 28]
     (identifier) ; [9:22 - 28]
    (block) ; [9:31 - 13:3]
     (resource_declaration) ; [10:5 - 12:5]
      type: (identifier) ; [10:5 - 11]
      title: (variable) ; [10:15 - 22]
       (identifier) ; [10:16 - 22]
      (attribute) ; [11:7 - 25]
       name: (identifier) ; [11:7 - 12]
       value: (identifier) ; [11:17 - 25]
  (comment) ; [15:3 - 31]
  (variable) ; [16:3 - 11]
   (identifier) ; [16:4 - 11]
  (ERROR) ; [16:12 - 12]
  (identifier) ; [16:13 - 16]
  (ERROR) ; [16:18 - 18]
  (variable) ; [16:19 - 26]
   (identifier) ; [16:20 - 26]
  (ERROR) ; [16:27 - 17:11]
   (identifier) ; [17:5 - 11]
  (hash) ; [17:13 - 19:5]
   (attribute) ; [17:15 - 18:25]
    name: (variable) ; [17:15 - 18:12]
     (ERROR) ; [17:16 - 23]
      (identifier) ; [17:16 - 22]
     (identifier) ; [18:7 - 12]
    value: (identifier) ; [18:17 - 25]
(ERROR) ; [21:1 - 1]
```

It appears there are errors in the tree even with the first chained function call even though it does appear to highlight correctly. It is definitely much worse with the second chained function call. The function call is not identified and the block is being identified as a hash instead of as a code block.

**Comment by amaanq** [comment]
thank you that's a lot more helpful, iterators just weren't accounted for yet

**Comment by amaanq** [comment]
fixed now

**Comment by nvergottini** [comment]
I'm still not sure it is right. Here is a slightly modified example.

```puppet
# @summary Test class
class test {
  $packages = [
    'package1',
    'package2',
  ]

  if $packages.empty {
    fail('no packages provided')
  }

  # With empty parenthesis.
  $packages.each() |$package| {
    package { $package:
      ensure => installed,
    }
  }

  # Without empty parenthesis.
  $packages.each |$package| {
    package { $package:
      ensure => installed,
    }
  }
}
```

```
(comment) ; [1:1 - 21]
(class_definition) ; [2:1 - 25:1]
 (identifier) ; [2:7 - 10]
 (block) ; [2:12 - 25:1]
  (assignment) ; [3:3 - 6:3]
   (variable) ; [3:3 - 11]
    (identifier) ; [3:4 - 11]
   (array) ; [3:15 - 6:3]
    (string) ; [4:5 - 14]
     (string_content) ; [4:6 - 13]
    (string) ; [5:5 - 14]
     (string_content) ; [5:6 - 13]
  (if_statement) ; [8:3 - 10:3]
   (field_expression) ; [8:6 - 20]
    (variable) ; [8:6 - 14]
     (identifier) ; [8:7 - 14]
    (identifier) ; [8:16 - 20]
   (block) ; [8:22 - 10:3]
    (function_call) ; [9:5 - 32]
     (identifier) ; [9:5 - 8]
     (string) ; [9:10 - 31]
      (string_content) ; [9:11 - 30]
  (comment) ; [12:3 - 28]
  (function_call) ; [13:3 - 17:3]
   (field_expression) ; [13:3 - 16]
    (variable) ; [13:3 - 11]
     (identifier) ; [13:4 - 11]
    (identifier) ; [13:13 - 16]
   (lambda) ; [13:20 - 17:3]
    (variable) ; [13:21 - 28]
     (identifier) ; [13:22 - 28]
    (block) ; [13:31 - 17:3]
     (resource_declaration) ; [14:5 - 16:5]
      type: (identifier) ; [14:5 - 11]
      title: (variable) ; [14:15 - 22]
       (identifier) ; [14:16 - 22]
      (attribute) ; [15:7 - 25]
       name: (identifier) ; [15:7 - 12]
       value: (identifier) ; [15:17 - 25]
  (comment) ; [19:3 - 31]
  (iterator_statement) ; [20:3 - 24:3]
   iterator: (field_expression) ; [20:3 - 16]
    (variable) ; [20:3 - 11]
     (identifier) ; [20:4 - 11]
    (identifier) ; [20:13 - 16]
   (variable) ; [20:19 - 26]
    (identifier) ; [20:20 - 26]
   (block) ; [20:29 - 24:3]
    (resource_declaration) ; [21:5 - 23:5]
     type: (identifier) ; [21:5 - 11]
     title: (variable) ; [21:15 - 22]
      (identifier) ; [21:16 - 22]
     (attribute) ; [22:7 - 25]
      name: (identifier) ; [22:7 - 12]
      value: (identifier) ; [22:17 - 25]
```

The first each is treated as a function call with a lambda, but only the second is treated as an iterator. I also see now that the use of **empty** without parenthesis in the if statement no longer produces an error, but it isn't treated as a function. I can see that it would be a problem treating it as a function without the parenthesis if Puppet supported accessing hash elements using dotted notation, but it doesn't.

I do appreciate the quick response. This fix at least makes it much more usable.
